version: '3'
services:
  redis:
    image: redis:latest
    command: redis-server --requirepass root123
    ports:
      - "6379:6379"
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
  qqchat:
    image: openjdk:latest
    volumes:
      - ./QQChat-0.0.1-SNAPSHOT.jar:/QQChat-0.0.1-SNAPSHOT.jar
    command: java -jar /QQChat-0.0.1-SNAPSHOT.jar
    ports:
      - "8099:8099"
    depends_on:
      - mysql
      - redis