version: '3' # docker-compose版本
services: # 服务列表
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
#    volumes:
#      - ./sql/init.sql